---
layout:     post
title:      python常用异常处理
subtitle:   python 异常类型
date:       2019-04-06
author:     ChrisChou
header-img: img/post-bg-coffee.jpeg
catalog: true
tags:
    - Python
---

python本身的异常处理是非常友好的

把你期望正常运行的代码放入到try中在用except捕获你认为意外的错误再执行相应的处理

```python
try:
    pass
except Exception as err:
    print(err)

```

如

期望值是int类型：

```python
s1 = 'hello'
try:
    int(s1)
except ValueError as err:
    print(err)

```

期待的key不存在：

```python
dic = {'k1':'v1'}
try:
    dic['k20']
except KeyError as err:
    print(err)

```

超出索引范围：

```python
dic = ["wupeiqi", 'alex']
try:
    dic[10]
except IndexError as err:
    print(err)

```

常用错误异常：

AttributeError             试图访问一个对象没有的树形，比如foo.x，但是foo没有属性x  
IOError                      输入/输出异常；基本上是无法打开文件  
ImportError                无法引入模块或包；基本上是路径问题或名称错误  
IndentationError          语法错误（的子类） ；代码没有正确对齐  
IndexError                  下标索引超出序列边界，比如当x只有三个元素，却试图访问x\[5\]  
KeyError                    试图访问字典里不存在的键  
KeyboardInterrupt       Ctrl+C被按下  
NameError                 使用一个还未被赋予对象的变量  
SyntaxError                Python代码非法，代码不能编译(个人认为这是语法错误，写错了）  
TypeError                  传入对象类型与要求的不符合  
UnboundLocalError     试图访问一个还未被设置的局部变量，基本上是由于另有一个同名的全局变量，导致你以为正在访问它  
ValueError                 传入一个调用者不期望的值，即使值的类型是正确的

其他异常：

ArithmeticError  
AssertionError  
AttributeError  
BaseException  
BufferError  
BytesWarning  
DeprecationWarning  
EnvironmentError  
EOFError  
Exception  
FloatingPointError  
FutureWarning  
GeneratorExit  
ImportError  
ImportWarning  
IndentationError  
IndexError  
IOError  
KeyboardInterrupt  
KeyError  
LookupError  
MemoryError  
NameError  
NotImplementedError  
OSError  
OverflowError  
PendingDeprecationWarning  
ReferenceError  
RuntimeError  
RuntimeWarning  
StandardError  
StopIteration  
SyntaxError  
SyntaxWarning  
SystemError  
SystemExit  
TabError  
TypeError  
UnboundLocalError  
UnicodeDecodeError  
UnicodeEncodeError  
UnicodeError  
UnicodeTranslateError  
UnicodeWarning  
UserWarning  
ValueError  
Warning  
ZeroDivisionError

完整的异常处理结构

```python
try:
    # 主代码块
    pass
except KeyError,e:
    # 异常时，执行该块
    pass
else:
    # 主代码块执行完，执行该块
    pass
finally:
    # 无论异常与否，最终执行该块
    pass

```

主动抛出异常

```python
try:
    raise Exception('错误了。。。')
except Exception as err:
    print(err)

```

自定义异常

```python
class SelfException(Exception):
 
    def __init__(self, msg):
        self.message = msg
 
    def __str__(self):
        return self.message
 
try:
    raise SelfException('我的异常')
except SelfException as e:
    print(e)
```

对于必须出现我期望值的处理还有一种断言的方式，如果结果为false则抛出错误

python assert语法

例：

```python
assert 1==1
assert 2+2==2*2
assert len(['my boy',12])<10
assert range(4)==[0,1,2,3]
```

assert其实还有第二个参数assert expression \[, arguments\] ，第二个参数为抛出的错误信息

如：

```python
assert 2==1,'2不等于1'
```